### ISSUE TITLE
An item with the same key has already been added. Key: 90430???

### ISSUE THREAD

**Issue by Juzzotec** [13xforever/ps3-disc-dumper#48] opened 2023-11-19 09:35 UTC
Hi Team,

When trying to dump an iso, I get this error? what does it mean? I am trying to transform an iso via dameon tools iso mount to a format rspc3 can understand. I have done this with all other iso's but one game gives me this error.

![Screenshot 2023-11-19 203424](https://github.com/13xforever/ps3-disc-dumper/assets/91764289/5fcf9e37-58d3-4420-be8b-b98b85a61945)

**Comment by 13xforever** [comment] 2023-11-19 09:54
Duplicate of #45, but also no support per #36

**Closed by 13xforever** 2023-11-19 09:54 UTC

**Comment by Juzzotec** [comment] 2023-11-19 10:07
understood but what does the error mean?
