### ISSUE TITLE
Invalid Characters in game name causes "Invalid argument" System.IO.IOException error

### ISSUE THREAD

**Issue by Shroomerian** [13xforever/ps3-disc-dumper#20] opened 2022-02-17 17:52 UTC
System: Manjaro Linux
App Version: v.3.2.1

Steps to reproduce: 

1. Put in a disc of a game which contains a "™" character and mount it.
2. Use the PS3 disc dumper app.
3. Wait for the disc to be first read
4. See "Invalid argument" error

This error seems to be caused by the **System.IO.Directory.CreateDirectory(String path)** function and the **System.IO.FileSystem.CreateDirectory(String fullPath)** as described in the log output at the end of the file. This error occured when I tried to dump **"[BCES01175] Uncharted 3: Drake's Deception™"**

[2022-02-17.log](https://github.com/13xforever/ps3-disc-dumper/files/8090955/2022-02-17.log)

This error can be circumvented by automatically removing the characters which are causing problem **and or** allowing the user to rename the output path of the file with a --rename variable, the ladder being more versatile since invalid characters can depend from system to system.

Thank you for the trouble and thank you so much for making such an incredible tool! :+1:

**Comment by 13xforever** [comment] 2022-02-17 21:09
Trademark is not an issue, unless you have weird codepage configured gor your filesystem, and I already strip it among other stuff, just for more readable titles. I'll look at the log on weekend.

**Comment by Shroomerian** [comment] 2022-02-20 16:09
Figured it out. On Manjaro Linux **":"** is an illegal character. Either way there should be an option to rename the output name of the folder for these cases.

**Comment by 13xforever** [comment] 2022-02-20 16:11
again, it depends on the filesystem and I already filter out characters that are not valid according to the runtime/system

**Comment by Shroomerian** [comment] 2022-02-20 16:12
> again, it depends on the filesystem and I already filter out characters that are not valid according to the runtime/system

**Comment by 13xforever** [comment] 2022-02-20 16:15
Please don't close the issue when I haven't even had a chance to dig out the root cause

**Closed** 2022-02-20 16:36 UTC
Labels: bug, needs more information

**Comment by 13xforever** [comment] 2022-02-20 16:41
Please try the new build 3.2.2, it should work

**Comment by Shroomerian** [comment] 2022-02-20 16:51
The same issue still occurs. The output name still contains **":"** and thus it can't create a folder with that name.

[2022-02-20.log](https://github.com/13xforever/ps3-disc-dumper/files/8104440/2022-02-20.log)

**Comment by 13xforever** [comment] 2022-02-20 16:59
Are you dumping to an NTFS mount? Because Linux native filesystems can use `:` just fine

**Comment by Shroomerian** [comment] 2022-02-20 17:03
> Are you dumping to an NTFS mount? Because Linux native filesystems can use `:` just fine

Omg you are right! I can dump perfectly on an ext4 drive. Thanks for guiding me!

**Comment by 13xforever** [comment] 2022-02-20 17:05
I've updated the linux build of 3.2.2 to explicitly remove most common windows-specific characters
