### ISSUE TITLE
Problem, dont work 

### ISSUE THREAD

**Issue by Ludek1988** [13xforever/ps3-disc-dumper#56] opened 2024-01-28 23:57 UTC
![Screenshot_1](https://github.com/13xforever/ps3-disc-dumper/assets/157178022/7b02af51-abaf-4ef5-92c3-6755906f20bb)
![Screenshot_2](https://github.com/13xforever/ps3-disc-dumper/assets/157178022/593f6241-a503-4841-9326-f7d712e05f85)

I have a key for this game but it doesn't work for me, why?

**Comment by Ludek1988** [comment] 2024-01-29 00:00
![Screenshot_3](https://github.com/13xforever/ps3-disc-dumper/assets/157178022/8c4e73b8-f1ee-4b04-9a56-161327b10e09)
![Screenshot_4](https://github.com/13xforever/ps3-disc-dumper/assets/157178022/37317a50-cdaf-490d-b0c8-930ef5d131d2)
![Screenshot_5](https://github.com/13xforever/ps3-disc-dumper/assets/157178022/7b20c783-65b2-43df-b707-8655d35ea12a)

**Comment by 13xforever** [comment] 2024-01-29 05:19
Duplicate of #49

**Closed** 2024-01-29 05:20 UTC
Labels: invalid, needs more information
