### ISSUE TITLE
No valid disc decryption key was found erro during disk redump

### ISSUE THREAD

**Issue by MaxBeliar** [13xforever/ps3-disc-dumper#44] opened 2023-08-31 16:53 UTC
Hello!
Could not redump the ISO files.

Check on v4.0.2, v4.0.3, v3.3.5
No result for 2 ISO (BLES-00016, BCES-00226)
.ird files were found and downloaded

2023-08-31 08:43:52	38191	INFO	Updated settings: {
  "OutputDir": "C:\\Users\\\u041C\u0430\u043A\u0441\u0438\u043C\\Downloads\\ps3-disc-dumper_windows_v4.0.3",
  "IrdDir": "C:\\Users\\\u041C\u0430\u043A\u0441\u0438\u043C\\Downloads\\ps3-disc-dumper_windows_v4.0.3",
  "DumpNameTemplate": "%title% [%product_code%]",
  "ShowDetails": true,
  "EnableTransparency": true,
  "PreferSystemAccent": false,
  "StayOnTop": false
}
2023-08-31 08:43:54	40139	INFO	Selected disc: F:\
2023-08-31 08:43:54	40140	DEBUG	Disc flags: gu
2023-08-31 08:43:54	40140	DEBUG	Disc product code: BCES-00226
2023-08-31 08:43:54	40140	INFO	Game title: Resistance 2™
2023-08-31 08:43:54	40161	DEBUG	Dump folder name: Resistance 2 [BCES00226]
2023-08-31 08:43:54	40161	TRACE	Getting keys from IrdProvider...
2023-08-31 08:43:54	40162	TRACE	Searching local cache for a match...
2023-08-31 08:43:54	40162	TRACE	Searching for IRDs using 2 sources for a match...
2023-08-31 08:43:57	43431	INFO	Found 2 new IRD matches
2023-08-31 08:43:57	43431	DEBUG	Trying to download 0E389DDD_B1B2ACFE_5214BFAD_520E2546.ird from ps3ird.free.fr...
2023-08-31 08:43:58	43677	DEBUG	Trying to download BCES00226-B70EB41D7022D72FB8EE0BD654C37DC1.ird from ps3.aldostools.org...
2023-08-31 08:43:58	43923	INFO	Found 1 IRD files
2023-08-31 08:43:58	43923	TRACE	Got 1 keys
2023-08-31 08:43:58	43923	TRACE	Getting keys from RedumpProvider...
2023-08-31 08:43:58	43923	INFO	Using locally cached redump keys snapshot
2023-08-31 08:43:58	43943	INFO	Found 4092 redump keys
2023-08-31 08:43:58	43943	TRACE	Loading loose cached redump keys
2023-08-31 08:43:58	43944	INFO	Found 0 cached disc keys
2023-08-31 08:43:58	43944	TRACE	Got 4092 keys
2023-08-31 08:43:58	43945	TRACE	Trying to enumerate physical drives...
2023-08-31 08:44:01	46775	INFO	Found optical media drive DTSOFT Virtual CdRom Device (F:)
2023-08-31 08:44:01	46775	DEBUG	Found 1 physical drives
2023-08-31 08:44:01	46775	TRACE	Checking physical drive \\.\CDROM0...
2023-08-31 08:44:01	46776	TRACE	Found PS3_DISC.SFB, getting sector data...
2023-08-31 08:44:01	46776	TRACE	PS3_DISC.SFB sector number is 832, reading content...
2023-08-31 08:44:01	46776	DEBUG	Selected physical drive \\.\CDROM0
2023-08-31 08:44:01	46777	DEBUG	Using \PS3_GAME\USRDIR\EBOOT.BIN for disc key detection
2023-08-31 08:44:01	46777	DEBUG	Initialized sectorIV (128 bit) for sector 10346: 0000000000000000000000000000286a
2023-08-31 08:44:01	46799	ERROR	Failed to find a matching key
System.Collections.Generic.KeyNotFoundException: No valid disc decryption key was found
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()

[v4_0_2-2023-08-31.log](https://github.com/13xforever/ps3-disc-dumper/files/12488476/v4_0_2-2023-08-31.log)
[v3_3_5-2023-08-31.log](https://github.com/13xforever/ps3-disc-dumper/files/12488479/v3_3_5-2023-08-31.log)

Probably the problem is in the local cache. Could you help?

**Comment by 13xforever** [comment] 2023-08-31 17:20
Duplicate of #36

**Closed** 2023-08-31 17:20 UTC
