### ISSUE TITLE
can not work properly

### ISSUE THREAD

**Issue by whoever2023** [13xforever/ps3-disc-dumper#38] opened 2023-07-26 02:14 UTC
I do not know what happened to it, it can not work properly when i tried to decrypt redump iso. 
always got the same log below

"2023-07-26 09:47:18	54545	DEBUG	Selected physical drive \\.\CDROM1
2023-07-26 09:47:18	54549	DEBUG	Using \PS3_GAME\LICDIR\LIC.DAT for disc key detection
2023-07-26 09:47:18	54549	DEBUG	Initialized sectorIV (128 bit) for sector 2112: 00000000000000000000000000000840
2023-07-26 09:47:18	54592	ERROR	Failed to find matching key
System.AggregateException: One or more errors occurred. (No valid disc decryption key was found)
 ---> System.Collections.Generic.KeyNotFoundException: No valid disc decryption key was found"

but i checked the ird directoy and i am sure the relevant key has been downloaded successfully.
just a few days ago I can decrypt succefully the same iso that i was testing today.I am sure the iso is ok,so i guess something must be wrong with this excellent tool.would you please check it out.thank you very much.

**Comment by 13xforever** [comment] 2023-07-26 06:48
duplicate of #36

**Closed by 13xforever** 2023-07-26 06:48 UTC
