### ISSUE TITLE
Program freze in file 11 when trying to dump Metal Gear solid 4 platinum edition. 

### ISSUE THREAD

**Issue by Borgoxs001** [13xforever/ps3-disc-dumper#77] opened 2024-10-04 03:02 UTC
Im triying to Dump my ps3 Platinum edition of this game and it frezes every time it reach file 11. It appear to keep working but every time i do something with my pc it frezes fully.  The Thing is that is a big game and the Ird database dont specify for platinum keys. The otter problem is that I dont know how to use Redump keys or how to produce this keys with my MANAGUNZ on my Ps3. Some Guide will help.

**Comment by 13xforever** [comment] 2024-10-04 19:00
You didn't provide any logs, so I can't say with 100% certainty, but it's almost certainly means your disc is damaged and your drive can't read some sectors.

Duplicate of #74.

**Closed by 13xforever** 2024-10-04 19:00 UTC

**Comment by Borgoxs001** [comment] 2024-10-05 15:56
Hello there. I dump It using the Managunz with the decrypt iso option. Then transferred it to my pc with a pendrive I mount with windows. And use your program to dump the game and it did the job.
So I'm going to check if the game dump with no errors later. And I will try to dump it your program again and send you a video prove of the problem.
Sorry to ask men. What's the log and where I can find it?

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 13xforever** [comment] 2024-10-05 16:00
You can find the log at the bottom of the Settings.
