### ISSUE TITLE
Direct disk access to the drive was denied.

### ISSUE THREAD

**Issue by sawyermade** [13xforever/ps3-disc-dumper#47] opened 2023-10-26 13:52 UTC
As title says, no matter what I do it keeps saying "Direct disk access to the drive was denied". I am on Windows 11 Pro and mounting a redump iso. I tried running as admin but it gave me an error when I did that. Here is the log file...

```
2023-10-26 09:46:58	10	INFO	Loading settings…
2023-10-26 09:46:58	872	INFO	PS3 Disc Dumper v4.0.5
2023-10-26 09:46:59	917	INFO	Selected disc: H:\
2023-10-26 09:46:59	929	DEBUG	Disc flags: gu
2023-10-26 09:46:59	930	DEBUG	Disc product code: BLUS-30166
2023-10-26 09:46:59	943	INFO	Game title: BioShock
2023-10-26 09:46:59	943	INFO	Game product code: BLUS30166
2023-10-26 09:46:59	943	INFO	Game version: 01.00
2023-10-26 09:46:59	943	INFO	App version: 01.00
2023-10-26 09:46:59	1018	DEBUG	Dump folder name: BioShock [BLUS30166]
2023-10-26 09:46:59	1023	TRACE	Getting keys from IrdProvider...
2023-10-26 09:46:59	1039	TRACE	Searching local cache for a match...
2023-10-26 09:46:59	1066	TRACE	Searching for IRDs using 2 sources for a match...
2023-10-26 09:47:01	3080	INFO	Found 5 new IRD matches
2023-10-26 09:47:01	3080	DEBUG	Trying to download BAF2C1CB_8BF0F901_D8D8F979_4E041910.ird from ps3ird.free.fr...
2023-10-26 09:47:01	3589	DEBUG	Trying to download BAF2C1CB_8BF0F901_D8D8F979_D70D48AA.ird from ps3ird.free.fr...
2023-10-26 09:47:02	4092	DEBUG	Trying to download 245960DA_1E7FBCFB_49040B14_1C087370.ird from ps3ird.free.fr...
2023-10-26 09:47:02	4486	DEBUG	Trying to download BLUS30166-75C286B6BFCE3554EA1A506A67C2BE65.ird from ps3.aldostools.org...
2023-10-26 09:47:02	4567	DEBUG	Trying to download BLUS30166-4742C12D9E4DE372AD2754C9F028CD2F.ird from ps3.aldostools.org...
2023-10-26 09:47:02	4640	INFO	Found 9 IRD files
2023-10-26 09:47:02	4640	TRACE	Got 9 keys from IrdProvider
2023-10-26 09:47:02	4640	TRACE	Getting keys from RedumpProvider...
2023-10-26 09:47:04	6531	INFO	Latest redump snapshot: Sony - PlayStation 3 - Disc Keys (4282) (2023-10-24 19-55-09).zip
2023-10-26 09:47:04	6532	INFO	Saving latest redump snapshot in local cache: Sony - PlayStation 3 - Disc Keys (4282) (2023-10-24 19-55-09).zip...
2023-10-26 09:47:04	6533	INFO	Using locally cached redump keys snapshot
2023-10-26 09:47:04	6570	INFO	Found 4101 redump keys
2023-10-26 09:47:04	6570	TRACE	Loading loose cached redump keys
2023-10-26 09:47:04	6570	INFO	Found 0 cached disc keys
2023-10-26 09:47:04	6570	TRACE	Got 4101 keys from RedumpProvider
2023-10-26 09:47:04	6572	TRACE	Trying to enumerate physical drives...
2023-10-26 09:47:07	9865	INFO	Found optical media drive Microsoft Virtual DVD-ROM (H:)
2023-10-26 09:47:07	9865	DEBUG	Found 1 physical drives
2023-10-26 09:47:07	9865	TRACE	Checking physical drive \\.\CDROM0...
2023-10-26 09:47:07	9866	DEBUG	Skipping drive \\.\CDROM0: Access to the path '\\.\CDROM0' is denied.
2023-10-26 09:47:07	9867	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()
2023-10-26 09:47:42	6	INFO	Loading settings…
2023-10-26 09:47:43	812	INFO	PS3 Disc Dumper v4.0.5
2023-10-26 09:47:43	854	INFO	Selected disc: H:\
2023-10-26 09:47:43	856	DEBUG	Disc flags: gu
2023-10-26 09:47:43	857	DEBUG	Disc product code: BLUS-30166
2023-10-26 09:47:43	860	INFO	Game title: BioShock
2023-10-26 09:47:43	860	INFO	Game product code: BLUS30166
2023-10-26 09:47:43	860	INFO	Game version: 01.00
2023-10-26 09:47:43	860	INFO	App version: 01.00
2023-10-26 09:47:43	884	DEBUG	Dump folder name: BioShock [BLUS30166]
2023-10-26 09:47:43	890	TRACE	Getting keys from IrdProvider...
2023-10-26 09:47:43	892	TRACE	Searching local cache for a match...
2023-10-26 09:47:43	918	TRACE	Searching for IRDs using 2 sources for a match...
2023-10-26 09:47:45	2751	DEBUG	No matching IRD file was found at any source
2023-10-26 09:47:45	2751	INFO	Found 9 IRD files
2023-10-26 09:47:45	2751	TRACE	Got 9 keys from IrdProvider
2023-10-26 09:47:45	2751	TRACE	Getting keys from RedumpProvider...
2023-10-26 09:47:47	4467	INFO	Latest redump snapshot: Sony - PlayStation 3 - Disc Keys (4282) (2023-10-24 19-55-09).zip
2023-10-26 09:47:47	4467	INFO	Using local copy of redump key snapshot
2023-10-26 09:47:47	4468	INFO	Using locally cached redump keys snapshot
2023-10-26 09:47:47	4507	INFO	Found 4101 redump keys
2023-10-26 09:47:47	4507	TRACE	Loading loose cached redump keys
2023-10-26 09:47:47	4508	INFO	Found 0 cached disc keys
2023-10-26 09:47:47	4508	TRACE	Got 4101 keys from RedumpProvider
2023-10-26 09:47:47	4509	TRACE	Trying to enumerate physical drives...
2023-10-26 09:47:50	7751	INFO	Found optical media drive Microsoft Virtual DVD-ROM (H:)
2023-10-26 09:47:50	7751	DEBUG	Found 1 physical drives
2023-10-26 09:47:50	7751	TRACE	Checking physical drive \\.\CDROM0...
2023-10-26 09:47:50	7752	DEBUG	Skipping drive \\.\CDROM0: Access to the path '\\.\CDROM0' is denied.
2023-10-26 09:47:50	7753	ERROR	Failed to find a matching key
System.AccessViolationException: Direct disk access to the drive was denied
   at Ps3DiscDumper.Dumper.FindDiscKeyAsync(String discKeyCachePath)
   at UI.Avalonia.ViewModels.MainViewModel.ScanDiscsAsync()

```

**Comment by 13xforever** [comment] 2023-10-26 14:00
duplicate of #36

**Closed by 13xforever** 2023-10-26 14:00 UTC
