### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by Jax-505** [13xforever/ps3-disc-dumper#42] opened 2023-08-08 12:38 UTC
Can't Detect KEY Even I Try With Latest Version 4 Its Continue Showing Looking For Disk Key  
Can You Solve This problem ?

**Comment by 13xforever** [comment] 2023-08-08 12:46
I can't conjure disc keys, so no. Double so when you provide zero details and no log.

Duplicate of #41

**Closed by 13xforever** 2023-08-08 12:46 UTC
